FROM node:20-alpine

WORKDIR /app


ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG RESEND_API_KEY


ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV RESEND_API_KEY=$RESEND_API_KEY

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
